In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv",sep=";")

In [4]:
data.shape

(1599, 12)

In [5]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
train,test=train_test_split(data)
train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
395,12.0,0.37,0.76,4.2,0.066,7.0,38.0,1.00040,3.22,0.60,13.0,7
1524,6.0,0.42,0.19,2.0,0.075,22.0,47.0,0.99522,3.39,0.78,10.0,6
639,8.9,0.29,0.35,1.9,0.067,25.0,57.0,0.99700,3.18,1.36,10.3,6
844,9.9,0.25,0.46,1.7,0.062,26.0,42.0,0.99590,3.18,0.83,10.6,6
144,5.2,0.34,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.0,6
...,...,...,...,...,...,...,...,...,...,...,...,...
1329,7.4,0.60,0.26,2.1,0.083,17.0,91.0,0.99616,3.29,0.56,9.8,6
674,10.8,0.40,0.41,2.2,0.084,7.0,17.0,0.99840,3.08,0.67,9.3,6
622,10.0,0.58,0.22,1.9,0.080,9.0,32.0,0.99740,3.13,0.55,9.5,5
1416,10.0,0.32,0.59,2.2,0.077,3.0,15.0,0.99940,3.20,0.78,9.6,5
1315,7.5,0.63,0.27,2.0,0.083,17.0,91.0,0.99616,3.26,0.58,9.8,6

In [8]:
test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
736,7.7,0.965,0.10,2.1,0.112,11.0,22.0,0.99630,3.26,0.50,9.5,5
225,7.7,0.430,0.25,2.6,0.073,29.0,63.0,0.99615,3.37,0.58,10.5,6
384,7.7,0.510,0.28,2.1,0.087,23.0,54.0,0.99800,3.42,0.74,9.2,5
77,6.8,0.785,0.00,2.4,0.104,14.0,30.0,0.99660,3.52,0.55,10.7,6
1133,7.2,0.480,0.07,5.5,0.089,10.0,18.0,0.99684,3.37,0.68,11.2,7
...,...,...,...,...,...,...,...,...,...,...,...,...
254,7.1,0.600,0.00,1.8,0.074,16.0,34.0,0.99720,3.47,0.70,9.9,6
850,9.3,0.430,0.44,1.9,0.085,9.0,22.0,0.99708,3.28,0.55,9.5,5
302,8.3,0.705,0.12,2.6,0.092,12.0,28.0,0.99940,3.51,0.72,10.0,5
1334,7.2,0.835,0.00,2.0,0.166,4.0,11.0,0.99608,3.39,0.52,10.0,5
116,8.3,0.540,0.28,1.9,0.077,11.0,40.0,0.99780,3.39,0.61,10.0,6